Algoritmo "DivididoPor11Resto5"
//Faça o fluxograma e pseudocódigo para um
//programa que mostre a quantidade de
//números entre 1000 e 2000 e que, quando
//divididos por 11, produzam resto igual a 5.
Var
       numero:inteiro
       calculo:real
Inicio
      para numero de 1000 ate 2000 passo 1 faca
         calculo <- numero mod 11
         se (calculo = 5) entao
              escreval(numero," tem resto ",calculo)
         fimse
      fimpara

Fimalgoritmo