Algoritmo "semnome"

procedimento ola (nome:caractere)
var

inicio
   escreval("ola ", nome, " mundo, eu estou em um procendimento")
fimprocedimento



procedimento ola2(quantidade:inteiro)

var
   cont:inteiro
   nome2:caractere
inicio

   para cont de 1 ate quantidade passo 1 faca
      leia(nome2)
      escreval("Boa noite ",nome2)
   fimpara


fimprocedimento




Var

Inicio
   ola("Jose")
   ola2(5)
Fimalgoritmo