Algoritmo "Tabuada"
//4. Faça um fluxograma e pseudocódigo que receba
//um número e mostre a tabuada da
//multiplicação para esse número.
Var
       numero ,tabuada:inteiro
       calculo:real
Inicio
      tabuada <- 0
      escreva("Digite um numero")
      leia(numero)
      
      para tabuada de 0 ate 10 passo 1 faca
           calculo <- numero * tabuada
          escreval(numero," X ",tabuada,"=",calculo)
      
      fimpara
Fimalgoritmo